namespace: grafana
helm:
  chart: https://grafana.github.io/helm-charts/packages/grafana-8.14.0.tgz
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev
