defaultNamespace: grafana
helm:
  releaseName: grafana
  chart: grafana
  repo: https://grafana.github.io/helm-charts
  version: 8.14.0
  # Don't specify valuesFiles here globally if doing per-env below

targetCustomizations:
- name: dev
  clusterSelector:
    matchLabels:
      env: dev
  helm:
    valuesFiles:
      - values-dev.yaml

- name: prod
  clusterSelector:
    matchLabels:
      env: prod
  helm:
    valuesFiles:
      - values-prod.yaml